### ISSUE TITLE
setting a watch fails with AttributeError: 'ModelizedStreamResponse' object has no attribute 'raw'

### ISSUE THREAD

**Issue by pjz** [Revolution1/etcd3-py#105]
* etcd3-py version: 0.1.6
* Python version: 3.7
* Operating System: linux

### Description

I was trying to get a watch working in my app.  It's currently complex, but if you have no idea why this is happening, I'll work on getting a stripped-down version working.

If it matters, I'm using an async client.

### What I Did

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/tmp/xgw-venv/lib/python3.7/site-packages/etcd3/stateful/watch.py", line 283, in run
    for event in self:
  File "/tmp/xgw-venv/lib/python3.7/site-packages/etcd3/stateful/watch.py", line 356, in __iter__
    if not self._resp or self._resp.raw.closed:
AttributeError: 'ModelizedStreamResponse' object has no attribute 'raw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/xgw-venv/lib/python3.7/site-packages/etcd3/stateful/watch.py", line 284, in run
    self.dispatch_event(event)
  File "/tmp/xgw-venv/lib/python3.7/site-packages/etcd3/stateful/watch.py", line 338, in __exit__
    self.stop()
  File "/tmp/xgw-venv/lib/python3.7/site-packages/etcd3/stateful/watch.py", line 295, in stop
    self._kill_response_stream()
  File "/tmp/xgw-venv/lib/python3.7/site-packages/etcd3/stateful/watch.py", line 260, in _kill_response_stream
    if not self._resp or (self._resp and self._resp.raw.closed):
AttributeError: 'ModelizedStreamResponse' object has no attribute 'raw'```

**Comment by Revolution1** [comment]
async stateful util not supported, yet.

I opened a issuse https://github.com/Revolution1/etcd3-py/issues/16 long time ago, if you need this feature, I can try starting working on it.

**Comment by pjz** [comment]
Is there a watch feature that _does_ support async?  I can maybe use that instead.

**Comment by Revolution1** [comment]
yes, you can use raw api `client.watch_create` instead

https://github.com/Revolution1/etcd3-py/blob/master/etcd3/stateful/watch.py#L386-L417

**Comment by pjz** [comment]
Hm. Given that I'm having difficulty understanding how it's all supposed to work, I should take you up on your offer to fix this feature for me.  While you do that, I'll try and wrap my head around how the lower-level watch stuff works so I can maybe lend a hand.

**Comment by Revolution1** [comment]
okay

**Comment by pjz** [comment]
Any progress on this?

**Comment by pjz** [comment]
is there (failing) test code for this?

**Comment by andr-c** [comment]
Meanwhile, this is how async watch works for me (in case somheone may still need it):
       
       ```
def get_range_end(prefix):
            return prefix[:-1] + chr(ord(prefix[-1]) + 1)

async def on_event(self, key, value, type):
           # your K/V event processing code here
           pass

async with etcd_client.watch_create(prefix, range_end=get_range_end(prefix)) as r:
            async for msg in r:
                log.info(msg)
                if msg.events:
                    for event in msg.events:
                        try:
                            await on_event(event.kv.key, event.kv.value, event.type)
                        except Exception as e:
                            log.exception(f'Failed to process event : {event}')
```

**Comment by agronholm** [comment]
This really should be in the documentation! The current docs give me absolutely no clue on how to use most of the async stuff.

**Comment by Vasiliy566** [comment]
@andr-c It is not correct way because it block event loop and it is no way to stop watch for async client, so until the  author adds full async features supports we have no way to async client + watcher.

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by pgonzalezgebo** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @Molly-Blockchain, @jmgiacalone, @franz101, @polymath-on, @vico4445, @vivienbcr, @chys1203

**Comment by pgonzalezgebo** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @dg3feiko, @FutureBody, @vivek8031, @abstraction, @christiankywong, @bitthal, @yusufonur
