### ISSUE TITLE
use Lock in python 2.6 will cause "error: release unlocked lock" problem

### ISSUE THREAD

**Issue by richieyan** [Revolution1/etcd3-py#121]
* etcd3-py version: 0.1.6
* Python version: 2.7.9
* Operating System: Debian 4.9.88 amd64

### Description

when lock job is done, the release action in lease.py will cause error, becuase `Lock` is not reentrant lock.

### What I Did

```
In [4]: with etcd_client.Lock('test_this_is_key', lock_ttl=30) as lock:
    print lock.is_acquired
    time.sleep(15)
    print 'job done'
   ...:
True
job done

In [5]: Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/data/apps/demo/eggs/etcd3_py-0.1.6-py2.7.egg/etcd3/stateful/lease.py", line 163, in keepalived
    log.exception("cancel_cb() raised an error")
error: release unlocked lock
```

**Comment by Revolution1** [comment]
❓
