### ISSUE TITLE
Install fails using pip>=20.1

### ISSUE THREAD

**Issue by pjz** [Revolution1/etcd3-py#138]
* etcd3-py version: current
* Python version: 3.7
* Operating System: any

### Description
```
pip install --upgrade pip  # gets you to pip > 20.1
pip install etcd3-py
...

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2ys2e_8z/etcd3-py/setup.py", line 36, in <module>
        requirements = [str(ir.req) for ir in install_reqs]
      File "/tmp/pip-install-2ys2e_8z/etcd3-py/setup.py", line 36, in <listcomp>
        requirements = [str(ir.req) for ir in install_reqs]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
```
### Cause
pip changed their internals; see https://github.com/pypa/pip/issues/8188#issuecomment-623428010

**Comment by heitorPB** [comment]
@pjz did you find a fix for that? I am also hitting this error.

**Comment by Revolution1** [comment]
@heitorPB This lib is not maintained for years 😂 
Fankly, this lib be very buggy or even not usable for etcd nowadays.
I also haven't use etcd directly for long time.
Maybe you should try some other lib.
