### ISSUE TITLE
Username/password authentication not working ?

### ISSUE THREAD

**Issue by jsfrerot** [Revolution1/etcd3-py#41]
* etcd3-py version: 0.1.5
* Python version:3.6.7
* Operating System: Ubuntu 18.10

### Description
Authentication seems to be not working

### What I Did

```
>>> from etcd3 import Client
>>> client = Client(host='my_etcd_host',protocol='https', verify='/etc/ssl/certs/ca-certificates.crt', username='myuser', password='mypassword')
>>> client.version()
EtcdVersion(etcdserver='3.3.10', etcdcluster='3.3.0')
>>> client.put('foo', 'bar')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jsfrerot/code/python_envs/etcd_client/lib/python3.6/site-packages/etcd3/apis/kv.py", line 106, in put
    return self.call_rpc(method, data=data)
  File "/home/jsfrerot/code/python_envs/etcd_client/lib/python3.6/site-packages/etcd3/client.py", line 199, in call_rpc
    self._raise_for_status(resp)
  File "/home/jsfrerot/code/python_envs/etcd_client/lib/python3.6/site-packages/etcd3/client.py", line 148, in _raise_for_status
    raise get_client_error(error, code, status, resp)
etcd3.errors.go_etcd_rpctypes_error.ErrUserEmpty: <ErrUserEmpty error:'etcdserver: user name is empty', code:3>


```

**Comment by Revolution1** [comment]
thank you for your report, I'm working on it

**Comment by Revolution1** [comment]
@jsfrerot turns out you just need to call client.auth() before you call other apis.

etcd3-py won't detect if the auth is enabled for you, you have to call the auth function by your self.

I will try to make this more human friendly.
