### ISSUE TITLE
catching exceptions/errors

### ISSUE THREAD

**Issue by jsfrerot** [Revolution1/etcd3-py#80]
* etcd3-py version: 0.1.5
* Python version: 3.6
* Operating System: Ubuntu 18.04

### Description

Not able to catch exceptions, how do we handle errors ?

### What I Did

```
from etcd3.errors import Etcd3Exception
try:
    nb_keys = self.client.range(key, count_only=True)
except Etcd3Exception as e:

  File "/home/jsfrerot/code/python_envs/symapid/lib/python3.6/site-packages/etcd3/client.py", line 148, in _raise_for_status
    raise get_client_error(error, code, status, resp)
etcd3.errors.go_etcd_rpctypes_error.ErrInvalidAuthToken: <ErrInvalidAuthToken error:'etcdserver: invalid auth token', code:16>
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/opt/2T/git/symapid/symapid/services/etcd.py", line 52, in key_exists
    nb_keys = self.client.range(key, count_only=True)
TypeError: catching classes that do not inherit from BaseException is not allowed


```

**Comment by jsfrerot** [comment]
Nevermind, this was not a problem at all. This is generated by my own code !
